export default {
  onChange: "onChange",
  setActiveItemIndex: "setActiveItemIndex",
  CAMBIARSTATE: "CAMBIARSTATE",
  onKeyPress: "onKeyPress",
  eliminarFiltroTexto: "eliminarFiltroTexto",
  eliminarFiltroFamilia: "eliminarFiltroFamilia",
  eliminarFiltroGrupo: "eliminarFiltroGrupo",
  eliminarFiltroSubgrupo: "eliminarFiltroSubgrupo",
  eliminarFiltroMarca: "eliminarFiltroMarca",
  agregarItemCarrito: "agregarItemCarrito",
  sumarItem: "sumarItem",
  restarItem: "restarItem",
  agregarFamilia: "agregarFamilia",
  agregarGrupo: "agregarGrupo",
  agregarMarca: "agregarMarca",
  loginFacebook: "loginFacebook",
  guardarCliente: "guardarCliente",
  eliminarCliente: "eliminarCliente",
  login: "login",
  guardarPedidoNoRegistrado: "guardarPedidoNoRegistrado",
  editarCantidad: "editarCantidad",
  eliminarItem: "eliminarItem"
};
